import React from 'react';
import { Target, BookOpen, ClipboardCheck, HeartPulse } from 'lucide-react';
import CheckboxItem from '../../components/CheckboxItem';

const DeepenEngagement = () => {
  return (
    <div className="p-4 flex justify-center">
      <div className="max-w-7xl w-full">
        <h1 className="text-4xl font-light text-white mb-8 text-center bg-red-800 p-4 uppercase">Deepen Engagement (2-4 months)</h1>
        <div className="space-y-8">
          <section className="bg-white shadow-md rounded-lg p-6 text-left hover:shadow-lg transition-shadow">
            <div className="flex items-center mb-4">
              <Target className="w-8 h-8 text-red-800 mr-3" />
              <h2 className="text-2xl text-red-800">Increasing Responsibility</h2>
            </div>
            <ul className="pl-6 space-y-2 text-gray-700">
              <li>
                <CheckboxItem id="deepen-resp-1" text="Lead and oversee more substantial milestone tasks or entire projects" />
              </li>
              <li>
                <CheckboxItem id="deepen-resp-2" text="Leverage CCC resources and learnings to independently problem-solve" />
              </li>
              <li>
                <CheckboxItem id="deepen-resp-3" text="Facilitate direct communication with stakeholders, gauge risks, and issues" />
              </li>
            </ul>
          </section>

          <section className="bg-white shadow-md rounded-lg p-6 text-left hover:shadow-lg transition-shadow">
            <div className="flex items-center mb-4">
              <BookOpen className="w-8 h-8 text-red-800 mr-3" />
              <h2 className="text-2xl text-red-800">Knowledge Acquisition</h2>
            </div>
            <ul className="pl-6 space-y-2 text-gray-700">
              <li>
                <CheckboxItem id="deepen-know-1" text="Digest current roadmap, historical project data, and decisions" />
              </li>
              <li>
                <CheckboxItem id="deepen-know-2" text="Request targeted training on initiative-specific skills or knowledge" />
              </li>
              <li>
                <CheckboxItem id="deepen-know-3" text="Participate in or review past relevant internal or external training" />
              </li>
              <li>
                <CheckboxItem id="deepen-know-4" text="Develop Lessons Learned for institutional engagement, projects, and milestones" />
              </li>
            </ul>
          </section>

          <section className="bg-white shadow-md rounded-lg p-6 text-left hover:shadow-lg transition-shadow">
            <div className="flex items-center mb-4">
              <ClipboardCheck className="w-8 h-8 text-red-800 mr-3" />
              <h2 className="text-2xl text-red-800">Progress Review</h2>
            </div>
            <ul className="pl-6 space-y-2 text-gray-700">
              <li>
                <CheckboxItem id="deepen-progress-1" text="Weekly check-ins with supervisor" />
              </li>
              <li>
                <CheckboxItem id="deepen-progress-2" text="Mid-point (2-week) review of integration progress" />
              </li>
              <li>
                <CheckboxItem id="deepen-progress-3" text="Adjust onboarding plan as needed based on progress and feedback" />
              </li>
            </ul>
          </section>

          <section className="bg-white shadow-md rounded-lg p-6 text-left hover:shadow-lg transition-shadow">
            <div className="flex items-center mb-4">
              <HeartPulse className="w-8 h-8 text-red-800 mr-3" />
              <h2 className="text-2xl text-red-800">Capture Patient Impact</h2>
            </div>
            <ul className="pl-6 space-y-2 text-gray-700">
              <li>
                <CheckboxItem id="deepen-impact-1" text="Understand Value Creation through the Patient Impact Model" />
              </li>
              <li>
                <CheckboxItem id="deepen-impact-2" text="Map activities and impacts across relevant projects" />
              </li>
              <li>
                <CheckboxItem id="deepen-impact-3" text="Report Patient Impact generated by projects being run" />
              </li>
              <li>
                <CheckboxItem id="deepen-impact-4" text="Monitor indicators of value as a measure of success" />
              </li>
              <li>
                <CheckboxItem id="deepen-impact-5" text="LINK to Impact Form" />
              </li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default DeepenEngagement;